### ISSUE TITLE
Command In Readme didn't work

### ISSUE THREAD

**Issue by mbarkley** [expansel/errai-spring-boot-sample#1]
Really cool stuff!

The command in the readme (`mvn gwt:clean gwt:compile spring-boot:run`) didn't work for me. This is what I ended up using to run the demo:

    mvn clean compile gwt:compile spring-boot:run

**Comment by ruzkant** [comment]
Thanks Max appreciate the time you took to try it out. Will update the readme...

**Comment by BenDol** [comment]
This is really great, thanks for taking the time to put this together for the community. 🥇

**Comment by ruzkant** [comment]
It's a pleasure! (even more so to have the time for a change)
