### ISSUE TITLE
Breaks upon updating to Errai 4.1.0.Final & GWT 2.8.2 

### ISSUE THREAD

**Issue by BenDol** [expansel/errai-spring-boot-sample#2]
Any ideas what is going on with this?

**Comment by BenDol** [comment]
Only error I could find is this:
```
00:17:55 WARNING [SecurityContextImpl] Error received while attempting to populate cache: no subscribers to deliver to for subject: org.jboss.errai.security.shared.service.NonCachingUserService:RPC
```

**Comment by BenDol** [comment]
Seems since this commit https://github.com/errai/errai/commit/4f521d2dc56a967074e96529b81203673454f1ec#diff-5ce05f5ed2bd4263a8183b52eb6140b9 this [exception](https://github.com/errai/errai/commit/4f521d2dc56a967074e96529b81203673454f1ec#diff-5ce05f5ed2bd4263a8183b52eb6140b9R110) is never caught for what ever reason. Any ideas @mbarkley

**Comment by BenDol** [comment]
Fixed in my PR https://github.com/errai/errai/pull/304

**Comment by ruzkant** [comment]
Thanks for looking into this Ben!
