### ISSUE TITLE
Breaks when errai.bus.enable_web_socket_server=true is present in ErraiService.properties

### ISSUE THREAD

**Issue by BenDol** [expansel/errai-spring-boot-sample#3]
For some reason this property breaks things, any ideas why that is?

```
errai.bus.enable_web_socket_server=true
```

**Comment by ruzkant** [comment]
I have not used websockets before, but what I could find in the errai docs is that the above configuration enables a side band server on a different port. But there is also support for using jsr356 where a servlet is used which requires an additional dependency, one for CDI environment and a different one for non-CDI. See the following link:

[http://docs.jboss.org/errai/latest/errai/reference/html_single/#_jsr_356_websocket_support_deploying_to_wildfly_8_0_or_higher](url)

I am not sure if you specifically want the sideband server but to my inexperienced-with-websockets eyes the servlet option makes more sense, so I created a branch that demonstrates this support. Here is the commit reference:

[https://github.com/expansel/errai-spring-boot-sample/commit/b9cfc8c9c153bcd0df091ee771ddb268f457fd0e](url)

Let me know if that would satisfy your requirements.

Note: The app worked for me, but I was uncertain about whether the websockets are actually in use, so I inspected the heap and saw that it was being enabled and the ServerMessageBusCallback had a webSocketPath variable populated, from there I assumed it was being used.

**Comment by BenDol** [comment]
Wow thanks a lot! I'll check it out.

**Comment by ruzkant** [comment]
@BenDol Can I close this item? Are you satisfied with the servlet solution?

**Comment by BenDol** [comment]
Haven't touched websockets much since, I will probably revisit it at a later stage.
