### ISSUE TITLE
CSRF enabled is failing because the Errai service has its own CSRF protection

### ISSUE THREAD

**Issue by BenDol** [expansel/errai-spring-boot-sample#4]
Currently looking into resolving this, but if you have any ideas or input it will be greatly appreciated.

Thanks!

(using the issues as a task log in a way haha)

**Comment by BenDol** [comment]
Resolved in https://github.com/expansel/errai-spring-boot-sample/issues/4

**Comment by ruzkant** [comment]
@BenDol  I have done a release on errai-spring-server to 0.3.1 and merged this, so I am closing the issue, thanks a lot for your improvements!
